knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    # if true, enables the helper for PHP templates
    # support for templating is deprecated, it will be removed in next major version
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig