vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        user_image:
                uri_prefix: /images/user
                upload_destination: '%kernel.project_dir%/public/images/user'

        page_banner_image:
                uri_prefix: /images/page_banner
                upload_destination: '%kernel.project_dir%/public/images/page_banner'
        
        article_image:
                uri_prefix: /images/article
                upload_destination: '%kernel.project_dir%/public/images/article'
                namer:
                        service: Vich\UploaderBundle\Naming\PropertyNamer
                        options: { property: 'title' }

        member_image:
                uri_prefix: /images/member
                upload_destination: '%kernel.project_dir%/public/images/member'
                namer:
                        service: Vich\UploaderBundle\Naming\UniqidNamer
